[package]
name = "cosmic_gen"
version = "0.1.0"
edition = "2021"
description = "Deterministic generator for cosmic trees"
authors.workspace = true
license.workspace = true

[dependencies]
cosmic_core = { path = "../cosmic_core" }
rand = { version = "0.8", features = ["std"] }
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
